---
# Check OS compatibility
- fail: msg="Other OS then based on RedHat is not supported!"
  when: ansible_os_family != 'RedHat'

- name: Include optional user and group creation.
  when: (kibana_user_id is defined) and (kibana_group_id is defined)
  import_tasks: kibana-optional-user.yml

- name: Include specific Debian tasks
  import_tasks: kibana-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Include specific RedHat tasks
  import_tasks: kibana-RedHat.yml
  when: ansible_os_family == 'RedHat'
