# Check for mandatory parameters

- fail: msg="kibana_instance_name must be specified and cannot be blank"
  when: kibana_instance_name is not defined or kibana_instance_name == ''

# Use systemd for the following distributions:
#   Ubuntu 15 and up
#   Debian 8 and up
#   Centos 7 and up
# Relies on Kibana distribution installing a serviced script to determine whether one should be copied.
- set_fact: use_system_d={{ (ansible_distribution == 'Debian' and ansible_distribution_version is version_compare('8', '>=')) or (ansible_distribution in ['RedHat','CentOS'] and ansible_distribution_version is version_compare('7', '>=')) or (ansible_distribution == 'Ubuntu' and ansible_distribution_version is version_compare('15', '>=')) }}

- fail: msg="Host must use systemd!"
  when: not use_system_d

- set_fact: conf_dir={{ kibana_conf_dir }}/{{ kibana_instance_name }}
- set_fact: instance_init_script={{ init_script | dirname }}/{{ kibana_instance_name }}_{{ init_script | basename }}

- set_fact: instance_sysd_script={{ sysd_script | dirname }}/{{ kibana_instance_name }}_{{ sysd_script | basename}}
  when: use_system_d

# For directories we also use the {{ inventory_hostname }}-{{ kibana_instance_name }} - this helps if we have a shared SAN.
- set_fact: instance_suffix={{ inventory_hostname }}-{{ kibana_instance_name }}
- set_fact: pid_dir={{ kibana_pid_dir }}/{{ instance_suffix }}
- set_fact: log_dir={{ kibana_log_dir }}/{{ instance_suffix }}
- set_fact: data_dir={{ kibana_data_dir }}/{{ instance_suffix }}
