---
- name: Ensure libselinux-python on CentOS 6.x
  become: yes
  yum: name=libselinux-python state=present update_cache=yes
  when: ( ansible_distribution == "CentOS" ) and ( ansible_distribution_major_version == "6" )

- name: RedHat - add Elastic repo
  become: yes
  template: src=elastic.repo dest=/etc/yum.repos.d/elastic-{{ elastic_major_version }}.repo
  when: kibana_use_repository

- name: RedHat - Install Kibana
  become: yes
  yum: name=kibana{% if kibana_version is defined and kibana_version != ""  %}-{{ elastic_version }}{% endif %} state=present update_cache=yes
  when: kibana_use_repository
  register: redhat_kibana_install_from_repo
  notify: restart kibana
  until: '"failed" not in redhat_kibana_install_from_repo'
  retries: 5
  delay: 10

- name: RedHat - Install Kibana from url
  become: yes
  yum: name={% if kibana_custom_package_url is defined %}{{ kibana_custom_package_url }}{% else %}{{ kibana_package_url }}-{{ kibana_version }}.noarch.rpm{% endif %} state=present
  when: not kibana_use_repository
  register: kibana_install_from_package
  notify: restart kibana
