---
- name: os-specific vars
  include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - always

- name: check-set-parameters
  import_tasks: kibana-parameters.yml
  tags:
    - always

- import_tasks: java.yml
  when: kibana_java_install
  tags:
    - java

- import_tasks: kibana.yml
  tags:
    - install

- import_tasks: kibana-config.yml
  tags:
    - config

#- include_tasks: kibana-plugins.yml
#  when: kibana_plugins is defined or kibana_plugins_reinstall
#  tags:
#    - plugins

# We always execute xpack as we may need to remove features
- import_tasks: xpack/kibana-xpack.yml
  tags:
    - xpack

- meta: flush_handlers

- name: Make sure Kibana is started
  service: name={{ instance_init_script | basename }} state=started enabled=yes
  when: kibana_start_service

- name: Wait for Kibana to startup
  wait_for: host={{ kibana_api_host }} port={{ kibana_api_port }} delay=5 connect_timeout=1
  when: kibana_restarted is defined and kibana_restarted.changed and kibana_start_service
