
- name: reload systemd configuration
  become: yes
  command: systemctl daemon-reload

# Restart service and ensure it is enabled
- name: restart kibana
  become: yes
  service: name={{ instance_init_script | basename }} state=restarted enabled=yes
  when:
    - kibana_restart_on_change
    - kibana_start_service
  register: kibana_restarted

- name: iptables save
  command: service iptables save
